### ISSUE TITLE
如何部署 cdn

### ISSUE THREAD

**Issue by zyzzyh** [cnbloglabs/awescnb#36]
我想将主题相关资源部署到自己的 cdn 上，请问我应当怎么做，谢谢。

**Comment by zyzzyh** [comment]
在博客园使用皮肤

**Comment by guangzan** [comment]
@zyzzyh https://www.yuque.com/awescnb/pugltk/zimn8cbxvm1dg1g1

**Comment by zyzzyh** [comment]
感谢
